export const CATEGORY_IMAGE_MAP: Record<number, string> = {
  1: 'assets/category-images/din.svg',
  2: 'assets/category-images/geography.svg',
  3: 'assets/category-images/history.svg',
  4: 'assets/category-images/football.svg',
  5: 'assets/category-images/math.svg',
  6: 'assets/category-images/general.svg',
  7: 'assets/category-images/movies.svg',
  8: 'assets/category-images/science.svg',
  9: 'assets/category-images/technology.svg',
  10: 'assets/category-images/riddles.svg',

  11: 'assets/category-images/egypt_old_days.svg',
  12: 'assets/category-images/egyptian_cinema_stars.svg',
  13: 'assets/category-images/egyptian_music.svg',
  14: 'assets/category-images/egyptian_series.svg',
  15: 'assets/category-images/egyptian_proverbs.svg',
  16: 'assets/category-images/egyptian_food.svg',
  17: 'assets/category-images/egypt_governorates.svg',
  18: 'assets/category-images/egypt_landmarks.svg',
  19: 'assets/category-images/egyptian_figures.svg',
  20: 'assets/category-images/egyptian_dialect.svg',
  21: 'assets/category-images/egyptian_sports.svg',
  22: 'assets/category-images/inventions.svg',
  23: 'assets/category-images/human_body.svg',
  24: 'assets/category-images/animals_birds.svg',
  25: 'assets/category-images/plants_nature.svg',
  26: 'assets/category-images/space_astronomy.svg',
  27: 'assets/category-images/video_games.svg',
  28: 'assets/category-images/internet_social.svg',
  29: 'assets/category-images/brands_companies.svg',
  30: 'assets/category-images/cars_transport.svg',

  31: 'assets/category-images/alahly.svg',
  32: 'assets/category-images/egyptian_league.svg',
  33: 'assets/category-images/premier_league.svg',
  34: 'assets/category-images/ballon_dor.svg',
  35: 'assets/category-images/capitals.svg',
  36: 'assets/category-images/country_flags.svg',

  37: 'assets/category-images/egyptian_movie_quotes.svg',
  38: 'assets/category-images/egyptian_movie_posters.svg',
  39: 'assets/category-images/egyptian_series_intros.svg',
  40: 'assets/category-images/club_logos.svg',
  41: 'assets/category-images/world_stadiums.svg',
  42: 'assets/category-images/world_cup.svg',
  43: 'assets/category-images/champions_league.svg',
  44: 'assets/category-images/brand_logos.svg',
  45: 'assets/category-images/country_maps.svg',
  46: 'assets/category-images/who_am_i.svg',
  47: 'assets/category-images/guess_singer.svg',
  48: 'assets/category-images/guess_song_5_seconds.svg'
};

export function getCategoryImagePath(categoryId: number): string {
  return CATEGORY_IMAGE_MAP[categoryId] ?? 'assets/category-images/general.svg';
}